`timescale 1ns/1ps
// jev_dot_spi_tb.v -- self-checking testbench generated by the WASMApollo EDA; the expected
// values are the fabric's golden model (RefSim). Run: iverilog -o tb jev_dot_spi.v jev_dot_spi_tb.v && vvp tb

module jev_dot_spi_tb;
  reg clk = 1'b0;
  reg rst = 1'b1;
  reg spi_sclk = 0;
  reg spi_cs_n = 0;
  reg spi_mosi = 0;
  wire spi_miso;
  wire spi_miso_oe;
  wire irq;
  integer errors = 0;

  jev_dot_spi dut (.clk(clk), .rst(rst), .spi_sclk(spi_sclk), .spi_cs_n(spi_cs_n), .spi_mosi(spi_mosi), .spi_miso(spi_miso), .spi_miso_oe(spi_miso_oe), .irq(irq));

  always #5 clk = ~clk;
  task tick;
    begin
      @(posedge clk);
      #1;
    end
  endtask

  initial begin
    // vector 0
    spi_sclk = 1'h0;
    spi_cs_n = 1'h1;
    spi_mosi = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 0: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h0) begin $display("FAIL vector 0: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h0); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 0: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 1
    spi_sclk = 1'h1;
    spi_cs_n = 1'h1;
    spi_mosi = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 1: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h0) begin $display("FAIL vector 1: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h0); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 1: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 2
    spi_sclk = 1'h1;
    spi_cs_n = 1'h0;
    spi_mosi = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 2: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h1) begin $display("FAIL vector 2: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h1); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 2: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 3
    spi_sclk = 1'h0;
    spi_cs_n = 1'h0;
    spi_mosi = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 3: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h1) begin $display("FAIL vector 3: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h1); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 3: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 4
    spi_sclk = 1'h0;
    spi_cs_n = 1'h1;
    spi_mosi = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 4: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h0) begin $display("FAIL vector 4: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h0); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 4: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 5
    spi_sclk = 1'h1;
    spi_cs_n = 1'h1;
    spi_mosi = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 5: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h0) begin $display("FAIL vector 5: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h0); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 5: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 6
    spi_sclk = 1'h0;
    spi_cs_n = 1'h1;
    spi_mosi = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 6: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h0) begin $display("FAIL vector 6: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h0); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 6: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 7
    spi_sclk = 1'h1;
    spi_cs_n = 1'h0;
    spi_mosi = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 7: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h1) begin $display("FAIL vector 7: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h1); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 7: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 8
    spi_sclk = 1'h1;
    spi_cs_n = 1'h1;
    spi_mosi = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 8: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h0) begin $display("FAIL vector 8: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h0); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 8: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 9
    spi_sclk = 1'h1;
    spi_cs_n = 1'h0;
    spi_mosi = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 9: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h1) begin $display("FAIL vector 9: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h1); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 9: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 10
    spi_sclk = 1'h1;
    spi_cs_n = 1'h0;
    spi_mosi = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 10: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h1) begin $display("FAIL vector 10: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h1); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 10: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 11
    spi_sclk = 1'h1;
    spi_cs_n = 1'h0;
    spi_mosi = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 11: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h1) begin $display("FAIL vector 11: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h1); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 11: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 12
    spi_sclk = 1'h1;
    spi_cs_n = 1'h1;
    spi_mosi = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 12: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h0) begin $display("FAIL vector 12: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h0); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 12: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 13
    spi_sclk = 1'h1;
    spi_cs_n = 1'h0;
    spi_mosi = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 13: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h1) begin $display("FAIL vector 13: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h1); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 13: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 14
    spi_sclk = 1'h1;
    spi_cs_n = 1'h0;
    spi_mosi = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 14: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h1) begin $display("FAIL vector 14: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h1); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 14: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    // vector 15
    spi_sclk = 1'h0;
    spi_cs_n = 1'h1;
    spi_mosi = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (spi_miso !== 1'h0) begin $display("FAIL vector 15: spi_miso = %h, want %h", spi_miso, 1'h0); errors = errors + 1; end
    if (spi_miso_oe !== 1'h0) begin $display("FAIL vector 15: spi_miso_oe = %h, want %h", spi_miso_oe, 1'h0); errors = errors + 1; end
    if (irq !== 1'h0) begin $display("FAIL vector 15: irq = %h, want %h", irq, 1'h0); errors = errors + 1; end
    if (errors == 0) $display("PASS jev_dot_spi: 16 vectors");
    else $display("FAIL jev_dot_spi: %0d mismatches", errors);
    $finish;
  end
endmodule
