-- jev_dot_spi_tb.vhd -- self-checking testbench generated by the WASMApollo EDA; the expected
-- values are the fabric's golden model (RefSim). Run: ghdl -a jev_dot_spi.vhd jev_dot_spi_tb.vhd && ghdl -e jev_dot_spi_tb && ghdl -r jev_dot_spi_tb

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity jev_dot_spi_tb is
end entity jev_dot_spi_tb;

architecture sim of jev_dot_spi_tb is
  signal clk : std_logic := '0';
  signal rst : std_logic := '1';
  signal finished : boolean := false;
  signal spi_sclk : std_logic := '0';
  signal spi_cs_n : std_logic := '0';
  signal spi_mosi : std_logic := '0';
  signal spi_miso : std_logic;
  signal spi_miso_oe : std_logic;
  signal irq : std_logic;
begin
  dut : entity work.jev_dot_spi port map (clk => clk, rst => rst, spi_sclk => spi_sclk, spi_cs_n => spi_cs_n, spi_mosi => spi_mosi, spi_miso => spi_miso, spi_miso_oe => spi_miso_oe, irq => irq);
  clk <= not clk after 5 ns when not finished else '0';

  check : process
    variable errors : natural := 0;
    procedure tick is
    begin
      wait until rising_edge(clk);
      wait for 1 ns;
    end procedure;
  begin
    -- vector 0
    spi_sclk <= '0';
    spi_cs_n <= '1';
    spi_mosi <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 0: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '0' then
      report "FAIL vector 0: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 0: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 1
    spi_sclk <= '1';
    spi_cs_n <= '1';
    spi_mosi <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 1: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '0' then
      report "FAIL vector 1: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 1: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 2
    spi_sclk <= '1';
    spi_cs_n <= '0';
    spi_mosi <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 2: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '1' then
      report "FAIL vector 2: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 2: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 3
    spi_sclk <= '0';
    spi_cs_n <= '0';
    spi_mosi <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 3: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '1' then
      report "FAIL vector 3: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 3: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 4
    spi_sclk <= '0';
    spi_cs_n <= '1';
    spi_mosi <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 4: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '0' then
      report "FAIL vector 4: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 4: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 5
    spi_sclk <= '1';
    spi_cs_n <= '1';
    spi_mosi <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 5: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '0' then
      report "FAIL vector 5: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 5: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 6
    spi_sclk <= '0';
    spi_cs_n <= '1';
    spi_mosi <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 6: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '0' then
      report "FAIL vector 6: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 6: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 7
    spi_sclk <= '1';
    spi_cs_n <= '0';
    spi_mosi <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 7: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '1' then
      report "FAIL vector 7: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 7: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 8
    spi_sclk <= '1';
    spi_cs_n <= '1';
    spi_mosi <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 8: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '0' then
      report "FAIL vector 8: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 8: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 9
    spi_sclk <= '1';
    spi_cs_n <= '0';
    spi_mosi <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 9: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '1' then
      report "FAIL vector 9: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 9: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 10
    spi_sclk <= '1';
    spi_cs_n <= '0';
    spi_mosi <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 10: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '1' then
      report "FAIL vector 10: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 10: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 11
    spi_sclk <= '1';
    spi_cs_n <= '0';
    spi_mosi <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 11: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '1' then
      report "FAIL vector 11: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 11: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 12
    spi_sclk <= '1';
    spi_cs_n <= '1';
    spi_mosi <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 12: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '0' then
      report "FAIL vector 12: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 12: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 13
    spi_sclk <= '1';
    spi_cs_n <= '0';
    spi_mosi <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 13: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '1' then
      report "FAIL vector 13: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 13: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 14
    spi_sclk <= '1';
    spi_cs_n <= '0';
    spi_mosi <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 14: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '1' then
      report "FAIL vector 14: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 14: irq" severity error;
      errors := errors + 1;
    end if;
    -- vector 15
    spi_sclk <= '0';
    spi_cs_n <= '1';
    spi_mosi <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if spi_miso /= '0' then
      report "FAIL vector 15: spi_miso" severity error;
      errors := errors + 1;
    end if;
    if spi_miso_oe /= '0' then
      report "FAIL vector 15: spi_miso_oe" severity error;
      errors := errors + 1;
    end if;
    if irq /= '0' then
      report "FAIL vector 15: irq" severity error;
      errors := errors + 1;
    end if;
    if errors = 0 then
      report "PASS jev_dot_spi: 16 vectors";
    else
      report "FAIL jev_dot_spi: " & integer'image(errors) & " mismatches" severity failure;
    end if;
    finished <= true;
    wait;
  end process;
end architecture sim;
