// jev_dot_spi.v -- generated by the WASMApollo EDA (heapvm vgpu apollo) from typed fabric `jev_dot_spi`.
// 252 LUT4 cells, 112 word PEs, 63 registers, 11 combinational levels.
// Clocking matches the vFPGA / vASIC fabric: each rising clk edge latches every register
// from the settled levels; rst (synchronous) loads the fabric's initial state.
// Jev microcode ROM `route_x`: controller state -> Jev's answer -> select code (LSB first: rom_250 rom_251)
//   state  answer        p      code
//   0      x0            1.000  00
//   1      x1            1.000  01
//   2      x2            1.000  10
//   3      x3            1.000  11
// Jev microcode ROM `route_w`: controller state -> Jev's answer -> select code (LSB first: rom_252 rom_253)
//   state  answer        p      code
//   0      w0            1.000  00
//   1      w1            1.000  01
//   2      w2            1.000  10
//   3      w3            1.000  11
// Jev microcode ROM `mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_254)
//   state  answer        p      code
//   0      mac           1.000  1
//   1      mac           1.000  1
//   2      mac           1.000  1
//   3      mac           1.000  1

`timescale 1ns/1ps
module jev_dot_spi (
  input  wire        clk,
  input  wire        rst,
  input  wire spi_sclk,
  input  wire spi_cs_n,
  input  wire spi_mosi,
  output wire spi_miso,
  output wire spi_miso_oe,
  output wire irq
);

  function lut4(input [15:0] t, input [3:0] i);  // a LUT4 cell: row i of truth table t
    lut4 = t[i];
  endfunction

  // registers
  reg sck1 = 1'h0;
  reg sck2 = 1'h0;
  reg sck3 = 1'h0;
  reg cs1 = 1'h1;
  reg cs2 = 1'h1;
  reg cs3 = 1'h1;
  reg mo1 = 1'h0;
  reg mo2 = 1'h0;
  reg [31:0] rx = 32'h00000000;
  reg phase_0 = 1'h0;
  reg phase_1 = 1'h0;
  reg cnt_0 = 1'h0;
  reg cnt_1 = 1'h0;
  reg cnt_2 = 1'h0;
  reg cnt_3 = 1'h0;
  reg cnt_4 = 1'h0;
  reg is_w = 1'h0;
  reg sadr_0 = 1'h0;
  reg sadr_1 = 1'h0;
  reg sadr_2 = 1'h0;
  reg sadr_3 = 1'h0;
  reg rpend = 1'h0;
  reg wpend = 1'h0;
  reg ovf = 1'h0;
  reg lr = 1'h0;
  reg lw = 1'h0;
  reg wadr_0 = 1'h0;
  reg wadr_1 = 1'h0;
  reg wadr_2 = 1'h0;
  reg wadr_3 = 1'h0;
  reg [31:0] wdat = 32'h00000000;
  reg [31:0] rbuf = 32'h00000000;
  reg [31:0] opx0 = 32'h00000000;
  reg [31:0] opx1 = 32'h00000000;
  reg [31:0] opx2 = 32'h00000000;
  reg [31:0] opx3 = 32'h00000000;
  reg [31:0] opw0 = 32'h00000000;
  reg [31:0] opw1 = 32'h00000000;
  reg [31:0] opw2 = 32'h00000000;
  reg [31:0] opw3 = 32'h00000000;
  reg pend = 1'h0;
  reg irq_en = 1'h0;
  reg ack_q = 1'h0;
  reg [31:0] rdata = 32'h00000000;
  reg state_0 = 1'h0;
  reg state_1 = 1'h0;
  reg o_valid = 1'h0;
  reg o_mac = 1'h0;
  reg o_last = 1'h0;
  reg s_valid = 1'h0;
  reg s_mac = 1'h0;
  reg s_last = 1'h0;
  reg r_valid = 1'h0;
  reg [31:0] o_p = 32'h00000000;
  reg [31:0] s_p = 32'h00000000;
  reg [31:0] acc = 32'h00000000;
  reg [31:0] res = 32'h00000000;
  reg a_valid = 1'h0;
  reg a_mac = 1'h0;
  reg a_last = 1'h0;
  reg [31:0] a_x = 32'h00000000;
  reg [31:0] a_w = 32'h00000000;
  reg [31:0] tx = 32'h00000000;

  // level 0
  wire not_13 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, cs2});
  wire spi_rise_15 = lut4(16'h0404, {1'b0, sck3, sck2, cs2});
  wire [31:0] k_17 = 32'h00000001;
  wire [31:0] zext_19 = {31'b0, mo2};
  wire xnor_29 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, phase_0});
  wire xnor_30 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, phase_1});
  wire xnor_32 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, phase_0});
  wire xnor_33 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, phase_1});
  wire xnor_35 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, phase_0});
  wire xnor_36 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, phase_1});
  wire xnor_38 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, cnt_0});
  wire xnor_39 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, cnt_1});
  wire xnor_40 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, cnt_2});
  wire xnor_41 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, cnt_3});
  wire xnor_42 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, cnt_4});
  wire xnor_46 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, cnt_0});
  wire xnor_47 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, cnt_1});
  wire xnor_48 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, cnt_2});
  wire xnor_49 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, cnt_3});
  wire xnor_50 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, cnt_4});
  wire xor3_56 = lut4(16'h9696, {1'b0, 1'b0, 1'b1, cnt_0});
  wire maj_57 = lut4(16'hE8E8, {1'b0, 1'b0, 1'b1, cnt_0});
  wire [31:0] k_82 = 32'h00000007;
  wire [31:0] k_84 = 32'h00000001;
  wire [31:0] k_86 = 32'h00000000;
  wire [31:0] k_88 = 32'h00000001;
  wire [31:0] k_90 = 32'h00000001;
  wire [31:0] k_92 = 32'h00000001;
  wire [31:0] k_94 = 32'h00000002;
  wire [31:0] k_96 = 32'h00000001;
  wire [31:0] k_98 = 32'h00000003;
  wire [31:0] k_100 = 32'h00000001;
  wire not_127 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, rpend});
  wire mux_130 = lut4(16'hE4E4, {1'b0, sadr_0, wadr_0, rpend});
  wire mux_131 = lut4(16'hE4E4, {1'b0, sadr_1, wadr_1, rpend});
  wire mux_132 = lut4(16'hE4E4, {1'b0, sadr_2, wadr_2, rpend});
  wire mux_133 = lut4(16'hE4E4, {1'b0, sadr_3, wadr_3, rpend});
  wire rom_250 = lut4(16'hAAAA, {1'b0, 1'b0, state_1, state_0});
  wire rom_251 = lut4(16'hCCCC, {1'b0, 1'b0, state_1, state_0});
  wire rom_252 = lut4(16'hAAAA, {1'b0, 1'b0, state_1, state_0});
  wire rom_253 = lut4(16'hCCCC, {1'b0, 1'b0, state_1, state_0});
  wire rom_254 = lut4(16'hFFFF, {1'b0, 1'b0, state_1, state_0});
  wire xnor_255 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, state_0});
  wire xnor_256 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, state_1});
  wire nand_258 = lut4(16'h7777, {1'b0, 1'b0, s_valid, a_valid});
  wire xor3_260 = lut4(16'h9696, {1'b0, 1'b0, 1'b1, state_0});
  wire maj_261 = lut4(16'hE8E8, {1'b0, 1'b0, 1'b1, state_0});
  wire [31:0] pe3_278 = (a_x * a_w);
  wire not_279 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, s_valid});
  wire [31:0] pe1_297 = (acc + o_p);
  wire [31:0] k_300 = 32'h00000000;
  wire [31:0] k_322 = 32'h00000000;
  wire [31:0] k_324 = 32'h00000001;
  wire [31:0] k_326 = 32'h00000001;
  wire [31:0] k_328 = 32'h00000001;
  wire [31:0] zext_332 = {31'b0, pend};
  wire [31:0] zext_333 = {31'b0, r_valid};
  wire [31:0] k_334 = 32'h00000001;
  wire [31:0] zext_336 = {31'b0, irq_en};
  wire [31:0] k_337 = 32'h00000002;
  wire [31:0] k_341 = 32'h00000000;
  wire [31:0] k_342 = 32'h4A455644;
  wire and_359 = lut4(16'h8888, {1'b0, 1'b0, r_valid, irq_en});
  wire and_360 = lut4(16'h8888, {1'b0, 1'b0, lr, ack_q});
  wire and_361 = lut4(16'h8888, {1'b0, 1'b0, lw, ack_q});
  wire xor3_382 = lut4(16'h9696, {1'b0, 1'b0, 1'b1, sadr_0});
  wire maj_383 = lut4(16'hE8E8, {1'b0, 1'b0, 1'b1, sadr_0});
  wire [31:0] zext_399 = {31'b0, r_valid};
  wire [31:0] k_400 = 32'h0000001F;
  wire [31:0] zext_402 = {31'b0, pend};
  wire [31:0] k_403 = 32'h0000001E;
  wire [31:0] zext_406 = {31'b0, wpend};
  wire [31:0] k_407 = 32'h0000001D;
  wire [31:0] zext_409 = {31'b0, ovf};
  wire [31:0] k_410 = 32'h0000001C;
  wire not_415 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, is_w});
  wire [31:0] k_417 = 32'h00000001;
  wire [31:0] k_422 = 32'h0000001F;
  wire [31:0] k_424 = 32'h00000001;
  wire n426 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, sck1});
  wire n427 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, sck2});
  wire n428 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, cs1});
  wire n429 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, cs2});
  wire n430 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, mo1});
  wire n431 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, rpend});

  // level 1
  wire and_14 = lut4(16'h8888, {1'b0, 1'b0, cs3, not_13});
  wire [31:0] pe7_18 = (rx << (k_17 & 32'd31));
  wire and4_31 = lut4(16'h8000, {1'b1, 1'b1, xnor_30, xnor_29});
  wire and4_34 = lut4(16'h8000, {1'b1, 1'b1, xnor_33, xnor_32});
  wire and4_37 = lut4(16'h8000, {1'b1, 1'b1, xnor_36, xnor_35});
  wire and4_43 = lut4(16'h8000, {xnor_41, xnor_40, xnor_39, xnor_38});
  wire and4_44 = lut4(16'h8000, {1'b1, 1'b1, 1'b1, xnor_42});
  wire and4_51 = lut4(16'h8000, {xnor_49, xnor_48, xnor_47, xnor_46});
  wire and4_52 = lut4(16'h8000, {1'b1, 1'b1, 1'b1, xnor_50});
  wire xor3_58 = lut4(16'h9696, {1'b0, maj_57, 1'b0, cnt_1});
  wire maj_59 = lut4(16'hE8E8, {1'b0, maj_57, 1'b0, cnt_1});
  wire and_128 = lut4(16'h8888, {1'b0, 1'b0, not_127, wpend});
  wire xnor_151 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_130});
  wire xnor_152 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_131});
  wire xnor_153 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_132});
  wire xnor_154 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_133});
  wire xnor_156 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_130});
  wire xnor_157 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_131});
  wire xnor_158 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_132});
  wire xnor_159 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_133});
  wire xnor_161 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_130});
  wire xnor_162 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_131});
  wire xnor_163 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_132});
  wire xnor_164 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_133});
  wire xnor_166 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_130});
  wire xnor_167 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_131});
  wire xnor_168 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_132});
  wire xnor_169 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_133});
  wire xnor_171 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_130});
  wire xnor_172 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_131});
  wire xnor_173 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_132});
  wire xnor_174 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_133});
  wire xnor_176 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_130});
  wire xnor_177 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_131});
  wire xnor_178 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_132});
  wire xnor_179 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_133});
  wire xnor_181 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_130});
  wire xnor_182 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_131});
  wire xnor_183 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_132});
  wire xnor_184 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_133});
  wire xnor_186 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_130});
  wire xnor_187 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_131});
  wire xnor_188 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_132});
  wire xnor_189 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_133});
  wire xnor_191 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_130});
  wire xnor_192 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_131});
  wire xnor_193 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_132});
  wire xnor_194 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_133});
  wire xnor_196 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_130});
  wire xnor_197 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_131});
  wire xnor_198 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_132});
  wire xnor_199 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_133});
  wire xnor_201 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_130});
  wire xnor_202 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_131});
  wire xnor_203 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_132});
  wire xnor_204 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_133});
  wire xnor_206 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_130});
  wire xnor_207 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_131});
  wire xnor_208 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_132});
  wire xnor_209 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_133});
  wire xnor_211 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_130});
  wire xnor_212 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_131});
  wire xnor_213 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_132});
  wire xnor_214 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_133});
  wire xnor_216 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_130});
  wire xnor_217 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_131});
  wire xnor_218 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_132});
  wire xnor_219 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_133});
  wire xnor_221 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, mux_130});
  wire xnor_222 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_131});
  wire xnor_223 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_132});
  wire xnor_224 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_133});
  wire xnor_226 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_130});
  wire xnor_227 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_131});
  wire xnor_228 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_132});
  wire xnor_229 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, mux_133});
  wire and4_257 = lut4(16'h8000, {1'b1, 1'b1, xnor_256, xnor_255});
  wire and_259 = lut4(16'h8888, {1'b0, 1'b0, nand_258, pend});
  wire xor3_262 = lut4(16'h9696, {1'b0, maj_261, 1'b0, state_1});
  wire maj_263 = lut4(16'hE8E8, {1'b0, maj_261, 1'b0, state_1});
  wire [31:0] sel_267 = (rom_250 ? opx1 : opx0);
  wire [31:0] sel_268 = (rom_250 ? opx3 : opx2);
  wire [31:0] sel_271 = (rom_252 ? opw1 : opw0);
  wire [31:0] sel_272 = (rom_252 ? opw3 : opw2);
  wire and_280 = lut4(16'h8888, {1'b0, 1'b0, not_279, a_valid});
  wire [31:0] sel_298 = (o_mac ? pe1_297 : acc);
  wire [31:0] pe8_323 = (wdat >> (k_322 & 32'd31));
  wire [31:0] pe8_327 = (wdat >> (k_326 & 32'd31));
  wire [31:0] pe7_335 = (zext_333 << (k_334 & 32'd31));
  wire [31:0] pe7_338 = (zext_336 << (k_337 & 32'd31));
  wire [31:0] sel_343 = (mux_130 ? opx1 : opx0);
  wire [31:0] sel_344 = (mux_130 ? opx3 : opx2);
  wire [31:0] sel_345 = (mux_130 ? opw1 : opw0);
  wire [31:0] sel_346 = (mux_130 ? opw3 : opw2);
  wire [31:0] sel_348 = (mux_130 ? k_341 : k_341);
  wire [31:0] sel_349 = (mux_130 ? k_341 : k_341);
  wire [31:0] sel_350 = (mux_130 ? k_342 : k_341);
  wire not_364 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_361});
  wire not_368 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_360});
  wire [31:0] sel_381 = (and_360 ? rdata : rbuf);
  wire xor3_384 = lut4(16'h9696, {1'b0, maj_383, 1'b0, sadr_1});
  wire maj_385 = lut4(16'hE8E8, {1'b0, maj_383, 1'b0, sadr_1});
  wire [31:0] pe7_401 = (zext_399 << (k_400 & 32'd31));
  wire [31:0] pe7_404 = (zext_402 << (k_403 & 32'd31));
  wire [31:0] pe7_408 = (zext_406 << (k_407 & 32'd31));
  wire [31:0] pe7_411 = (zext_409 << (k_410 & 32'd31));
  wire [31:0] pe7_418 = (tx << (k_417 & 32'd31));
  wire [31:0] pe8_423 = (tx >> (k_422 & 32'd31));

  // level 2
  wire [31:0] pe5_20 = (pe7_18 | zext_19);
  wire and4_45 = lut4(16'h8000, {1'b1, 1'b1, and4_44, and4_43});
  wire and4_53 = lut4(16'h8000, {1'b1, 1'b1, and4_52, and4_51});
  wire xor3_60 = lut4(16'h9696, {1'b0, maj_59, 1'b0, cnt_2});
  wire maj_61 = lut4(16'hE8E8, {1'b0, maj_59, 1'b0, cnt_2});
  wire or_129 = lut4(16'hEEEE, {1'b0, 1'b0, and_128, rpend});
  wire not_147 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_128});
  wire and4_155 = lut4(16'h8000, {xnor_154, xnor_153, xnor_152, xnor_151});
  wire and4_160 = lut4(16'h8000, {xnor_159, xnor_158, xnor_157, xnor_156});
  wire and4_165 = lut4(16'h8000, {xnor_164, xnor_163, xnor_162, xnor_161});
  wire and4_170 = lut4(16'h8000, {xnor_169, xnor_168, xnor_167, xnor_166});
  wire and4_175 = lut4(16'h8000, {xnor_174, xnor_173, xnor_172, xnor_171});
  wire and4_180 = lut4(16'h8000, {xnor_179, xnor_178, xnor_177, xnor_176});
  wire and4_185 = lut4(16'h8000, {xnor_184, xnor_183, xnor_182, xnor_181});
  wire and4_190 = lut4(16'h8000, {xnor_189, xnor_188, xnor_187, xnor_186});
  wire and4_195 = lut4(16'h8000, {xnor_194, xnor_193, xnor_192, xnor_191});
  wire and4_200 = lut4(16'h8000, {xnor_199, xnor_198, xnor_197, xnor_196});
  wire and4_205 = lut4(16'h8000, {xnor_204, xnor_203, xnor_202, xnor_201});
  wire and4_210 = lut4(16'h8000, {xnor_209, xnor_208, xnor_207, xnor_206});
  wire and4_215 = lut4(16'h8000, {xnor_214, xnor_213, xnor_212, xnor_211});
  wire and4_220 = lut4(16'h8000, {xnor_219, xnor_218, xnor_217, xnor_216});
  wire and4_225 = lut4(16'h8000, {xnor_224, xnor_223, xnor_222, xnor_221});
  wire and4_230 = lut4(16'h8000, {xnor_229, xnor_228, xnor_227, xnor_226});
  wire mux_264 = lut4(16'hE4E4, {1'b0, xor3_260, state_0, and_259});
  wire mux_265 = lut4(16'hE4E4, {1'b0, xor3_262, state_1, and_259});
  wire and_266 = lut4(16'h8888, {1'b0, 1'b0, and4_257, and_259});
  wire [31:0] sel_269 = (rom_251 ? sel_268 : sel_267);
  wire [31:0] sel_273 = (rom_253 ? sel_272 : sel_271);
  wire mux_275 = lut4(16'hE4E4, {1'b0, rom_254, a_mac, and_259});
  wire mux_276 = lut4(16'hE4E4, {1'b0, and4_257, a_last, and_259});
  wire a_valid_next_277 = lut4(16'hEAEA, {1'b0, s_valid, a_valid, and_259});
  wire [31:0] sel_301 = (o_last ? k_300 : sel_298);
  wire [31:0] bit_325 = (pe8_323 & k_324);
  wire [31:0] bit_329 = (pe8_327 & k_328);
  wire [31:0] pe5_339 = (pe7_335 | pe7_338);
  wire [31:0] sel_351 = (mux_131 ? sel_344 : sel_343);
  wire [31:0] sel_352 = (mux_131 ? sel_346 : sel_345);
  wire [31:0] sel_354 = (mux_131 ? sel_350 : sel_349);
  wire and_365 = lut4(16'h8888, {1'b0, 1'b0, not_364, wpend});
  wire and_369 = lut4(16'h8888, {1'b0, 1'b0, not_368, rpend});
  wire xor3_386 = lut4(16'h9696, {1'b0, maj_385, 1'b0, sadr_2});
  wire maj_387 = lut4(16'hE8E8, {1'b0, maj_385, 1'b0, sadr_2});
  wire [31:0] pe5_405 = (pe7_401 | pe7_404);
  wire [31:0] pe5_412 = (pe7_408 | pe7_411);
  wire or_414 = lut4(16'hEEEE, {1'b0, 1'b0, and4_37, and4_34});
  wire [31:0] sel_419 = (spi_rise_15 ? pe7_418 : tx);
  wire [31:0] bit_425 = (pe8_423 & k_424);

  // level 3
  wire [31:0] sel_21 = (spi_rise_15 ? pe5_20 : rx);
  wire mux_54 = lut4(16'hE4E4, {1'b0, and4_53, and4_45, and4_37});
  wire xor3_62 = lut4(16'h9696, {1'b0, maj_61, 1'b0, cnt_3});
  wire maj_63 = lut4(16'hE8E8, {1'b0, maj_61, 1'b0, cnt_3});
  wire [31:0] pe8_83 = (pe5_20 >> (k_82 & 32'd31));
  wire [31:0] pe8_87 = (pe5_20 >> (k_86 & 32'd31));
  wire [31:0] pe8_91 = (pe5_20 >> (k_90 & 32'd31));
  wire [31:0] pe8_95 = (pe5_20 >> (k_94 & 32'd31));
  wire [31:0] pe8_99 = (pe5_20 >> (k_98 & 32'd31));
  wire wb_req_146 = lut4(16'h0808, {1'b0, ack_q, or_129, or_129});
  wire [31:0] sel_270 = (and_259 ? sel_269 : a_x);
  wire [31:0] sel_274 = (and_259 ? sel_273 : a_w);
  wire [31:0] pe5_340 = (zext_332 | pe5_339);
  wire [31:0] sel_355 = (mux_132 ? sel_352 : sel_351);
  wire not_372 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_365});
  wire xor3_388 = lut4(16'h9696, {1'b0, maj_387, 1'b0, sadr_3});
  wire maj_389 = lut4(16'hE8E8, {1'b0, maj_387, 1'b0, sadr_3});
  wire [31:0] pe5_413 = (pe5_405 | pe5_412);

  // level 4
  wire and_55 = lut4(16'h8888, {1'b0, 1'b0, mux_54, spi_rise_15});
  wire xor3_64 = lut4(16'h9696, {1'b0, maj_63, 1'b0, cnt_4});
  wire maj_65 = lut4(16'hE8E8, {1'b0, maj_63, 1'b0, cnt_4});
  wire mux_66 = lut4(16'hE4E4, {1'b0, 1'b0, xor3_56, mux_54});
  wire mux_67 = lut4(16'hE4E4, {1'b0, 1'b0, xor3_58, mux_54});
  wire mux_68 = lut4(16'hE4E4, {1'b0, 1'b0, xor3_60, mux_54});
  wire mux_69 = lut4(16'hE4E4, {1'b0, 1'b0, xor3_62, mux_54});
  wire [31:0] bit_85 = (pe8_83 & k_84);
  wire [31:0] bit_89 = (pe8_87 & k_88);
  wire [31:0] bit_93 = (pe8_91 & k_92);
  wire [31:0] bit_97 = (pe8_95 & k_96);
  wire [31:0] bit_101 = (pe8_99 & k_100);
  wire and_148 = lut4(16'h8888, {1'b0, 1'b0, not_147, wb_req_146});
  wire wb_wr_149 = lut4(16'h0808, {1'b0, pend, and_128, wb_req_146});
  wire [31:0] sel_347 = (mux_130 ? res : pe5_340);

  // level 5
  wire mux_70 = lut4(16'hE4E4, {1'b0, 1'b0, xor3_64, mux_54});
  wire mux_71 = lut4(16'hE4E4, {1'b0, mux_66, cnt_0, spi_rise_15});
  wire mux_72 = lut4(16'hE4E4, {1'b0, mux_67, cnt_1, spi_rise_15});
  wire mux_73 = lut4(16'hE4E4, {1'b0, mux_68, cnt_2, spi_rise_15});
  wire mux_74 = lut4(16'hE4E4, {1'b0, mux_69, cnt_3, spi_rise_15});
  wire and_81 = lut4(16'h8888, {1'b0, 1'b0, and4_31, and_55});
  wire mux_104 = lut4(16'hE4E4, {1'b0, 1'b0, 1'b1, bit_85[0]});
  wire mux_105 = lut4(16'hE4E4, {1'b0, 1'b1, 1'b0, bit_85[0]});
  wire or_150 = lut4(16'hEEEE, {1'b0, 1'b0, wb_wr_149, and_148});
  wire and_231 = lut4(16'h8888, {1'b0, 1'b0, and4_200, and_148});
  wire and_305 = lut4(16'h8888, {1'b0, 1'b0, and4_155, wb_wr_149});
  wire and_307 = lut4(16'h8888, {1'b0, 1'b0, and4_175, wb_wr_149});
  wire and_309 = lut4(16'h8888, {1'b0, 1'b0, and4_160, wb_wr_149});
  wire and_311 = lut4(16'h8888, {1'b0, 1'b0, and4_180, wb_wr_149});
  wire and_313 = lut4(16'h8888, {1'b0, 1'b0, and4_165, wb_wr_149});
  wire and_315 = lut4(16'h8888, {1'b0, 1'b0, and4_185, wb_wr_149});
  wire and_317 = lut4(16'h8888, {1'b0, 1'b0, and4_170, wb_wr_149});
  wire and_319 = lut4(16'h8888, {1'b0, 1'b0, and4_190, wb_wr_149});
  wire and_321 = lut4(16'h8888, {1'b0, 1'b0, and4_195, wb_wr_149});
  wire [31:0] sel_353 = (mux_131 ? sel_348 : sel_347);
  wire and_362 = lut4(16'h8888, {1'b0, 1'b0, and4_37, and_55});
  wire not_366 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, bit_85[0]});
  wire and4_416 = lut4(16'h8000, {1'b1, not_415, or_414, and_55});

  // level 6
  wire mux_75 = lut4(16'hE4E4, {1'b0, mux_70, cnt_4, spi_rise_15});
  wire mux_76 = lut4(16'hE4E4, {1'b0, mux_71, 1'b0, not_13});
  wire mux_77 = lut4(16'hE4E4, {1'b0, mux_72, 1'b0, not_13});
  wire mux_78 = lut4(16'hE4E4, {1'b0, mux_73, 1'b0, not_13});
  wire mux_79 = lut4(16'hE4E4, {1'b0, mux_74, 1'b0, not_13});
  wire mux_103 = lut4(16'hE4E4, {1'b0, bit_85[0], is_w, and_81});
  wire mux_106 = lut4(16'hE4E4, {1'b0, mux_104, 1'b0, and4_31});
  wire mux_107 = lut4(16'hE4E4, {1'b0, mux_105, 1'b1, and4_31});
  wire acc_ready_281 = lut4(16'hF7F7, {1'b0, and_231, r_valid, o_last});
  wire [31:0] sel_306 = (and_305 ? wdat : opx0);
  wire [31:0] sel_308 = (and_307 ? wdat : opw0);
  wire [31:0] sel_310 = (and_309 ? wdat : opx1);
  wire [31:0] sel_312 = (and_311 ? wdat : opw1);
  wire [31:0] sel_314 = (and_313 ? wdat : opx2);
  wire [31:0] sel_316 = (and_315 ? wdat : opw2);
  wire [31:0] sel_318 = (and_317 ? wdat : opx3);
  wire [31:0] sel_320 = (and_319 ? wdat : opw3);
  wire pend_next_330 = lut4(16'h88F8, {and_266, pend, bit_325[0], and_321});
  wire mux_331 = lut4(16'hE4E4, {1'b0, bit_329[0], irq_en, and_321});
  wire [31:0] sel_356 = (mux_132 ? sel_354 : sel_353);
  wire and_363 = lut4(16'h8888, {1'b0, 1'b0, is_w, and_362});
  wire and_367 = lut4(16'h8888, {1'b0, 1'b0, not_366, and_81});
  wire [31:0] sel_420 = (and4_416 ? rbuf : sel_419);

  // level 7
  wire mux_80 = lut4(16'hE4E4, {1'b0, mux_75, 1'b0, not_13});
  wire mux_108 = lut4(16'hE4E4, {1'b0, mux_106, phase_0, and_55});
  wire mux_109 = lut4(16'hE4E4, {1'b0, mux_107, phase_1, and_55});
  wire and_282 = lut4(16'h8888, {1'b0, 1'b0, acc_ready_281, o_valid});
  wire [31:0] sel_357 = (mux_133 ? sel_356 : sel_355);
  wire or_370 = lut4(16'hEEEE, {1'b0, 1'b0, and_369, and_367});
  wire or_371 = lut4(16'hEEEE, {1'b0, 1'b0, and_363, and_365});
  wire and_373 = lut4(16'h8888, {1'b0, 1'b0, not_372, and_363});
  wire and_379 = lut4(16'h8888, {1'b0, 1'b0, and_365, and_363});
  wire mux_390 = lut4(16'hE4E4, {1'b0, xor3_382, sadr_0, and_363});
  wire mux_391 = lut4(16'hE4E4, {1'b0, xor3_384, sadr_1, and_363});
  wire mux_392 = lut4(16'hE4E4, {1'b0, xor3_386, sadr_2, and_363});
  wire mux_393 = lut4(16'hE4E4, {1'b0, xor3_388, sadr_3, and_363});
  wire [31:0] sel_421 = (not_13 ? sel_420 : pe5_413);

  // level 8
  wire mux_110 = lut4(16'hE4E4, {1'b0, mux_108, 1'b0, not_13});
  wire mux_111 = lut4(16'hE4E4, {1'b0, mux_109, 1'b0, not_13});
  wire and_283 = lut4(16'h8888, {1'b0, 1'b0, s_valid, and_282});
  wire o_take_284 = lut4(16'hA2A2, {1'b0, and_282, o_valid, and_280});
  wire s_take_285 = lut4(16'h0808, {1'b0, and_282, o_valid, and_280});
  wire and_299 = lut4(16'h8888, {1'b0, 1'b0, o_last, and_282});
  wire [31:0] sel_302 = (and_282 ? sel_301 : acc);
  wire [31:0] sel_358 = (and_148 ? sel_357 : rdata);
  wire mux_374 = lut4(16'hE4E4, {1'b0, sadr_0, wadr_0, and_373});
  wire mux_375 = lut4(16'hE4E4, {1'b0, sadr_1, wadr_1, and_373});
  wire mux_376 = lut4(16'hE4E4, {1'b0, sadr_2, wadr_2, and_373});
  wire mux_377 = lut4(16'hE4E4, {1'b0, sadr_3, wadr_3, and_373});
  wire [31:0] sel_378 = (and_373 ? pe5_20 : wdat);
  wire ovf_next_380 = lut4(16'hF2F2, {1'b0, and_379, and_14, ovf});
  wire mux_394 = lut4(16'hE4E4, {1'b0, bit_89[0], mux_390, and_81});
  wire mux_395 = lut4(16'hE4E4, {1'b0, bit_93[0], mux_391, and_81});
  wire mux_396 = lut4(16'hE4E4, {1'b0, bit_97[0], mux_392, and_81});
  wire mux_397 = lut4(16'hE4E4, {1'b0, bit_101[0], mux_393, and_81});

  // level 9
  wire o_valid_next_286 = lut4(16'hEEFE, {and_282, o_valid, o_take_284, and_283});
  wire [31:0] sel_287 = (o_take_284 ? pe3_278 : o_p);
  wire mux_289 = lut4(16'hE4E4, {1'b0, a_mac, o_mac, o_take_284});
  wire mux_291 = lut4(16'hE4E4, {1'b0, a_last, o_last, o_take_284});
  wire s_valid_next_293 = lut4(16'hAEAE, {1'b0, and_283, s_valid, s_take_285});
  wire [31:0] sel_294 = (s_take_285 ? pe3_278 : s_p);
  wire mux_295 = lut4(16'hE4E4, {1'b0, a_mac, s_mac, s_take_285});
  wire mux_296 = lut4(16'hE4E4, {1'b0, a_last, s_last, s_take_285});
  wire [31:0] sel_303 = (and_299 ? sel_298 : res);
  wire r_valid_next_304 = lut4(16'hAEAE, {1'b0, and_231, r_valid, and_299});

  // level 10
  wire [31:0] sel_288 = (and_283 ? s_p : sel_287);
  wire mux_290 = lut4(16'hE4E4, {1'b0, s_mac, mux_289, and_283});
  wire mux_292 = lut4(16'hE4E4, {1'b0, s_last, mux_291, and_283});

  always @(posedge clk) begin
    if (rst) begin
      sck1 <= 1'h0;
      sck2 <= 1'h0;
      sck3 <= 1'h0;
      cs1 <= 1'h1;
      cs2 <= 1'h1;
      cs3 <= 1'h1;
      mo1 <= 1'h0;
      mo2 <= 1'h0;
      rx <= 32'h00000000;
      phase_0 <= 1'h0;
      phase_1 <= 1'h0;
      cnt_0 <= 1'h0;
      cnt_1 <= 1'h0;
      cnt_2 <= 1'h0;
      cnt_3 <= 1'h0;
      cnt_4 <= 1'h0;
      is_w <= 1'h0;
      sadr_0 <= 1'h0;
      sadr_1 <= 1'h0;
      sadr_2 <= 1'h0;
      sadr_3 <= 1'h0;
      rpend <= 1'h0;
      wpend <= 1'h0;
      ovf <= 1'h0;
      lr <= 1'h0;
      lw <= 1'h0;
      wadr_0 <= 1'h0;
      wadr_1 <= 1'h0;
      wadr_2 <= 1'h0;
      wadr_3 <= 1'h0;
      wdat <= 32'h00000000;
      rbuf <= 32'h00000000;
      opx0 <= 32'h00000000;
      opx1 <= 32'h00000000;
      opx2 <= 32'h00000000;
      opx3 <= 32'h00000000;
      opw0 <= 32'h00000000;
      opw1 <= 32'h00000000;
      opw2 <= 32'h00000000;
      opw3 <= 32'h00000000;
      pend <= 1'h0;
      irq_en <= 1'h0;
      ack_q <= 1'h0;
      rdata <= 32'h00000000;
      state_0 <= 1'h0;
      state_1 <= 1'h0;
      o_valid <= 1'h0;
      o_mac <= 1'h0;
      o_last <= 1'h0;
      s_valid <= 1'h0;
      s_mac <= 1'h0;
      s_last <= 1'h0;
      r_valid <= 1'h0;
      o_p <= 32'h00000000;
      s_p <= 32'h00000000;
      acc <= 32'h00000000;
      res <= 32'h00000000;
      a_valid <= 1'h0;
      a_mac <= 1'h0;
      a_last <= 1'h0;
      a_x <= 32'h00000000;
      a_w <= 32'h00000000;
      tx <= 32'h00000000;
    end else begin
      sck1 <= spi_sclk;
      sck2 <= n426;
      sck3 <= n427;
      cs1 <= spi_cs_n;
      cs2 <= n428;
      cs3 <= n429;
      mo1 <= spi_mosi;
      mo2 <= n430;
      rx <= sel_21;
      phase_0 <= mux_110;
      phase_1 <= mux_111;
      cnt_0 <= mux_76;
      cnt_1 <= mux_77;
      cnt_2 <= mux_78;
      cnt_3 <= mux_79;
      cnt_4 <= mux_80;
      is_w <= mux_103;
      sadr_0 <= mux_394;
      sadr_1 <= mux_395;
      sadr_2 <= mux_396;
      sadr_3 <= mux_397;
      rpend <= or_370;
      wpend <= or_371;
      ovf <= ovf_next_380;
      lr <= n431;
      lw <= and_128;
      wadr_0 <= mux_374;
      wadr_1 <= mux_375;
      wadr_2 <= mux_376;
      wadr_3 <= mux_377;
      wdat <= sel_378;
      rbuf <= sel_381;
      opx0 <= sel_306;
      opx1 <= sel_310;
      opx2 <= sel_314;
      opx3 <= sel_318;
      opw0 <= sel_308;
      opw1 <= sel_312;
      opw2 <= sel_316;
      opw3 <= sel_320;
      pend <= pend_next_330;
      irq_en <= mux_331;
      ack_q <= or_150;
      rdata <= sel_358;
      state_0 <= mux_264;
      state_1 <= mux_265;
      o_valid <= o_valid_next_286;
      o_mac <= mux_290;
      o_last <= mux_292;
      s_valid <= s_valid_next_293;
      s_mac <= mux_295;
      s_last <= mux_296;
      r_valid <= r_valid_next_304;
      o_p <= sel_288;
      s_p <= sel_294;
      acc <= sel_302;
      res <= sel_303;
      a_valid <= a_valid_next_277;
      a_mac <= mux_275;
      a_last <= mux_276;
      a_x <= sel_270;
      a_w <= sel_274;
      tx <= sel_421;
    end
  end

  // outputs
  assign spi_miso = bit_425[0];
  assign spi_miso_oe = not_13;
  assign irq = and_359;
endmodule
